# =========================================
# AI Providers
# =========================================
OPENAI_API_KEY="$OPENAI_API_KEY_ENV"

# =========================================
# Open WebUI (Docker compose)
# =========================================
OPEN_WEBUI_PORT="${OPEN_WEBUI_PORT_ENV}"
OPEN_WEBUI_CONFIG_PATH="${OPEN_WEBUI_CONFIG_PATH_ENV}"

# =========================================
# Media stack (Docker compose)
# =========================================

# Global
TZ="${TZ_ENV}"

# Shared media paths
MEDIA_DOWNLOADS_PATH="${MEDIA_DOWNLOADS_PATH_ENV}"
MEDIA_TV_PATH="${MEDIA_TV_PATH_ENV}"
MEDIA_MOVIES_PATH="${MEDIA_MOVIES_PATH_ENV}"

# qBittorrent
QBIT_PUID="${QBIT_PUID_ENV}"
QBIT_PGID="${QBIT_PGID_ENV}"
QBIT_WEBUI_PORT="${QBIT_WEBUI_PORT_ENV}"
QBIT_TORRENT_PORT="${QBIT_TORRENT_PORT_ENV}"
QBIT_CONFIG_PATH="${QBIT_CONFIG_PATH_ENV}"

# Sonarr
SONARR_PUID="${SONARR_PUID_ENV}"
SONARR_PGID="${SONARR_PGID_ENV}"
SONARR_PORT="${SONARR_PORT_ENV}"
SONARR_CONFIG_PATH="${SONARR_CONFIG_PATH_ENV}"

# Radarr
RADARR_PUID="${RADARR_PUID_ENV}"
RADARR_PGID="${RADARR_PGID_ENV}"
RADARR_PORT="${RADARR_PORT_ENV}"
RADARR_CONFIG_PATH="${RADARR_CONFIG_PATH_ENV}"

# Prowlarr
PROWLARR_PUID="${PROWLARR_PUID_ENV}"
PROWLARR_PGID="${PROWLARR_PGID_ENV}"
PROWLARR_PORT="${PROWLARR_PORT_ENV}"
PROWLARR_CONFIG_PATH="${PROWLARR_CONFIG_PATH_ENV}"

# Byparr
BYPARR_PORT="${BYPARR_PORT_ENV}"
